version: '3.9'
services:
  apis:
    container_name: muhammadridwan-api
    image: muhammadridwan-api:1.0.0
    build:
      context: .
      target: development
      dockerfile: Dockerfile
    command: npm run start
    ports:
      - 3000:3000
    networks:
      - nest-network
    depends_on:
      - mongodb
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    networks:
      - nest-network
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - nest-network
    restart: always
networks:
  nest-network:
    driver: bridge
